image: registry.gitlab.com/tftp/open/docker-maker:latest

stages:
  - build
  - release

.docker_dind: &docker_dind
  services:
    - name: docker:27.5.0-alpine3.21
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CONTAINER_REGISTRY
    - export TEST_IMAGE=$REGISTRY_PROJECT_URL/$BUILD_SUBPATH:${BUILD_ID}-test

# Common jobs variables
variables:
  CONTAINER_REGISTRY: registry.gitlab.com
  # Required variables for docker.mk
  REGISTRY_PROJECT_URL: $CONTAINER_REGISTRY/$CI_PROJECT_PATH
  BUILD_SUBPATH: dev
  BUILD_ID: $CI_COMMIT_SHORT_SHA
  REF_ID: $CI_COMMIT_REF_NAME

build:
  <<: *docker_dind
  stage: build
  script:
    - make ci-build ci-push

release:image:
  <<: *docker_dind
  stage: release
  script:
    - make ci-push-release
    - make -e REF_ID=latest ci-push-release
  only:
    - tags
    - master
